version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  webapp:
    image: interview-test.api
    container_name: webapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InterviewTestDb;User=sa;Password=@Passw0rd;Encrypt=True;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    ports:
      - "5000:8080"
    build:
      context: .
      dockerfile: Interview-Test.Api/Dockerfile
  
  angular:
    build:
      context: .
      dockerfile: Interview-Test.Client/Dockerfile
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=production
    container_name: interview-test-client
    restart: unless-stopped